### ISSUE TITLE
PyInstaller cannot find the humanize distribution

### ISSUE THREAD

**Issue by Gaoyongxian666** [jmoiron/humanize#105] opened 2020-02-13 11:30 UTC
I found this problem when I used the packaging program（pyinstaller） to package a python program.

It seems that there is a problem in retrieving the package. When I change back to the old version（v0.5.5）, there is no such problem

I'm a novice. I can't find any specific problems

![2020-02-13_192856](https://user-images.githubusercontent.com/35163802/74430110-34bc3800-4e97-11ea-889f-fe3c47e489fb.png)

**Comment by hugovk** [comment] 2020-02-13 12:49
Thanks for the report.

I'm not familiar with pyinstaller or wx, please can you give me step by step instructions on how to reproduce, along with any necessary config files?

What Python version are you using?

Where is it trying to retrieve the humanize distribution from?



> When I change back to the old version（v0.5.5）, there is no such problem

I presume you mean the 0.5.1, which was the last one before 1.0.0.

**Comment by hugovk** [comment] 2020-02-13 12:53
Also, if it's possible to run `wx` in verbose mode (maybe `wx -v` or `wx --verbose`), that might give more info.

**Comment by Gaoyongxian666** [comment] 2020-02-14 10:52
Yes,it is the 0.5.1.Of course, it's only when I use pyinstaller to package. There's no problem when I use it in Python.

I didn't use the library you wrote directly. I used someone else's library. He used your library in his library. His library name is uiautomator2. It's the one with the most stars.

WX-----This is a file I wrote myself. This file is useless.

**Comment by Gaoyongxian666** [comment] 2020-02-14 10:55
I can show you the steps. You can restore the environment, but I don't think it's very effective. Because it could be a problem with pyinstaller.

**Comment by Gaoyongxian666** [comment] 2020-02-14 11:00
For example, pyinstaller has a problem with the latest version 3.6. If the version of setuptools is too high, there will be a problem.

**Comment by Gaoyongxian666** [comment] 2020-02-14 11:15
As for pyinstaller, I don't know how he retrieved it. But if I reinstall humanize 0.5.1 and then use pyinstaller to package, there will be no problem

**Comment by Gaoyongxian666** [comment] 2020-02-14 11:23
Pyinstaller has a problem with the latest version 3.6. For example,If the version of setuptools is too high, there will be a problem.At that time, I had to reduce the version of my setuptools.Give you a reference：setuptools  45.2.0，this is too high，I use setuptools==40.
 For humanize,You can think of the difference between the latest two versions.

**Comment by Gaoyongxian666** [comment] 2020-02-14 11:24
574 INFO: Python: 3.6.6
575 INFO: Platform: Windows-10-10.0.18362-SP0

**Comment by 2press** [comment] 2020-03-04 20:44
The issue is with https://github.com/jmoiron/humanize/blob/b28d9ad895a1b2ef066c0b689b96bc50498554ba/src/humanize/__init__.py#L7

You can have a look at the discussion at https://github.com/googleapis/google-cloud-python/issues/1187 and https://github.com/pyinstaller/pyinstaller/issues/2294.

There is a workaround by creating `hook-humanize.py` and adding it to the hooks of pyinstaller:
```python
from PyInstaller.utils.hooks import copy_metadata

datas = copy_metadata('humanize')
```

**Comment by RyanLiuF** [comment] 2020-03-12 10:11
I have got the same problem too. 

ERROR:root:The 'humanize' distribution was not found and is required by the application
Traceback (most recent call last):
  File "main.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\program files\python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\uiautomator2\__init__.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\program files\python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\humanize\__init__.py", line 7, in <module>
  File "site-packages\pkg_resources\__init__.py", line 481, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 357, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 900, in require
  File "site-packages\pkg_resources\__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'humanize' distribution was not found and is required by the application

python version: 3.7.4
windows: 10
pyinstaller : 3.5

**Comment by RyanLiuF** [comment] 2020-03-12 10:37
Meanwhile, I am trying to install the version of 0.5.1, the problem is fixed, with the same version of pyinstaller and python.

**Comment by hugovk** [comment] 2020-03-12 10:47
@RyanLiuF Please use the workaround in https://github.com/jmoiron/humanize/issues/105#issuecomment-594826403.

**Comment by RyanLiuF** [comment] 2020-03-12 10:49
@hugovk of course, I have tried the workaround , but it doesn't work. thanks for your replay.

**Comment by 2press** [comment] 2020-03-12 16:36
Are you sure that the you have implemented the workaround correctly and that it is still not working? See https://github.com/teampheenix/StarCraft-Casting-Tool for an example.

If this is the case, please provide an complete minimal example.

**Comment by nicoddemus** [comment] 2021-05-26 21:14
Thanks @2press for providing the workaround.

I've opened https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/122 to include the hook in the standard PyInstaller hooks districution.

**Comment by hugovk** [comment] 2021-05-28 09:02
Thank you! https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/122 has been merged so let's close this.

**Closed by hugovk** 2021-05-28 09:02 UTC
